name: appthink_core
description: Appthink architecture core plugin
version: 0.16.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_local_notifications: ^18.0.1
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  async: ^2.11.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  app_links: ^6.3.3
  share_plus: ^10.1.3
  sprintf: ^7.0.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.5

dev_dependencies:
  golden_toolkit: ^0.15.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^3.0.0-0.0.dev

flutter:

