name: applithium_core
description: Applithium architecture core plugin
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.8
  flutter_bloc: ^7.1.0
  rxdart: ^0.27.1
  async: ^2.6.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^1.12.2
  copy_with_extension_gen: ^2.0.1
  mockito: ^5.0.4
  flutter_test:
    sdk: flutter

flutter:

