name: applithium_core
description: Applithium architecture core plugin
version: 0.9.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttertoast: ^8.0.8
  flutter_local_notifications: ^13.0.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.1
  async: ^2.6.1
  http: ^0.13.3
  shared_preferences: ^2.0.17
  uni_links: ^0.5.1
  share: ^2.0.4
  sprintf: ^6.0.0
  equatable: ^2.0.3
  freezed_annotation: ^2.1.0
  path_provider: ^2.0.12

dev_dependencies:
  golden_toolkit: ^0.13.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  freezed: 2.1.1

flutter:

